#metasfresh.properties
#Mon Mar 09 21:02:33 CST 2026
AdempiereSys=xyzN
AutoCommit=xyzY
AutoLogin=xyzN
AutoNew=xyzN
CDate=xyz2025-04-24 12\:12\:50.562
CacheWindow=xyzY
Charset=xyzUTF-8
Connection=xyzCConnection[DBhost\=localhost,DBport\=5432,DBname\=metasfresh,UID\=metasfresh,PWD\=metasfresh]
Language=xyz\u7B80\u4F53\u4E2D\u6587 (CN)
LoadTabMetaDataBackground=xyzN
OpenWindowMaximized=xyzY
PrintPreview=xyzN
ShowAcct=xyzY
ShowAdvanced=xyzY
ShowTrl=xyzN
SingleInstancePerWindow=xyzN
StorePassword=xyzY
TempDir=xyz/var/folders/tv/nvgfcf1x5bv2h227tjgr797r0000gn/T/
TraceFile=xyzN
TraceLevel=xyzWARNING
UILookFeel=xyzAdempiere
UITheme=xyzmetas Fresh Theme
ValidateConnectionOnStartup=xyzN
Warning=Do_not_change_any_of_the_data_as_they_will_have_undocumented_side_effects.
WarningD=Einstellungen_nicht_aendern,_da_diese_undokumentierte_Nebenwirkungen_haben.
