<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<artifactId>de.metas.parent</artifactId>
		<groupId>de.metas</groupId>
		<version>10.0.0</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<modelVersion>4.0.0</modelVersion>
	<groupId>de.metas.swat</groupId>
	<artifactId>de.metas.swat</artifactId>
	<packaging>pom</packaging>

    <description>SWAT (Sales and Warehouse Automation Tools) 销售和仓库自动化扩展模块，提供增强的销售流程、仓库管理和物流功能。</description>

	<modules>
		<module>de.metas.swat.base</module>
	</modules>

</project>
